YSMOD-168 Insert kodelister i db for
navikt/yrkesskade-kodeverk pull request #7
Opened 2022-04-01 10:31 UTC by erlendkri

- Tidsrom
  - Alvorlighetsgrad
  - Hvor skjedde ulykken
  - Årsak og bakgrunn
  - Skadet kroppsdel
  - Skadetype
  - Har skadelidt hatt fravær

Definisjonene av kodelistene ligger på https://confluence.adeo.no/display/MAYYMYFSN/Kodelister .  
  
Det er noen kodelister som ikke er ferdig definert ennå, så denne PR inneholder ikke alle kodelistene vi skal ha.

2022-04-01 13:55 UTC, olsnerik requested changes
Ser at testene har brukket; Spørringer på kodeverdier som nå gir tom liste. Ser også at spørringer på kategorier gir tom liste, f.eks. /api/v1/kodeverk/typer/skadetype/kategorier/.
Ellers litt småpirk.

2022-04-01 13:55 UTC, olsnerik commented on src/main/resources/db/migration/V2022_03_31_1400__aarsak_og_bakgrunn.sql
> +INSERT INTO kode (kode, kategori_id, type_id, gyldig_fra, gyldig_til, sortering) VALUES ('druktnetEllerBegravdEllerOmsvoept',              0, 3, '2022-03-15', null, 900);
Lurer på om det har sneket seg inn en "t" her i "druktnet"?

2022-04-01 13:55 UTC, olsnerik commented on src/main/resources/db/migration/V2022_03_31_1500__skadet_kroppsdel.sql
> +INSERT INTO kode (kode, kategori_id, type_id, gyldig_fra, gyldig_til, sortering) VALUES ('HoeyreSkulder',                0, 4, '2022-03-15', null, 1400);
Starte denne med liten h?

2022-04-01 13:55 UTC, olsnerik commented on src/main/resources/db/migration/V2022_04_01_1000__har_skadelidt_hatt_fravaer.sql
> +INSERT INTO verdi (kode, spraak, verdi) VALUES ('merEnnTreDager',      'nb', 'Kjent fravær mer enn tre dager ');
Skal verdien her ende med mellomrom?

2022-04-01 13:55 UTC, olsnerik commented on src/main/resources/db/migration/V2022_04_01_0930__skadetype.sql
> +INSERT INTO kode (kode, kategori_id, type_id, gyldig_fra, gyldig_til, sortering) VALUES ('akuttForgifning',         0, 5, '2022-03-15', null, 1100);
Her mangler det vel en t

2022-04-01 13:55 UTC, olsnerik commented on src/main/resources/db/migration/V2022_04_01_0930__skadetype.sql
> +INSERT INTO kode (kode, kategori_id, type_id, gyldig_fra, gyldig_til, sortering) VALUES ('knusningsSkade',          3, 5, '2022-03-29', null, 500);
Ikke noe big deal, men merker meg at denne har stor S på skade, mens f.eks. bloetdelsskade ikke har det. Bør vi velge én av skrivemåtene?

2022-04-01 13:55 UTC, olsnerik commented on src/main/resources/db/migration/V2022_04_01_0930__skadetype.sql
> +INSERT INTO type (type_id, navn, beskrivelse) VALUES (5, 'skadetype', 'Hva slag skade er det');
Her mangler det vel en s i "slag"

2022-04-04 09:22 UTC, erlendkri commented
Veldig bra gjennomgang, @olsnerik .
Kategoriliste fungerer fint hos meg; localhost:8080/api/v1/kodeverk/typer/tidsrom/kategorier
Har du slettet og opprettet lokal database pånytt?
Jeg får feil nå ved oppslag mot felles kodeverk, men lurer på om det skyldes at jeg ikke er på naisdevice? (kolide klager på os versjon). Kan du teste https://yrkesskade-kodeverk.dev.intern.nav.no/api/v1/kodeverk/typer/landkoder/kategorier/dummy/kodeverdier

2022-04-04 09:43 UTC, olsnerik commented
> Veldig bra gjennomgang, @olsnerik . Kategoriliste fungerer fint hos meg; localhost:8080/api/v1/kodeverk/typer/tidsrom/kategorier Har du slettet og opprettet lokal database pånytt? Jeg får feil nå ved oppslag mot felles kodeverk, men lurer på om det skyldes at jeg ikke er på naisdevice? (kolide klager på os versjon). Kan du teste https://yrkesskade-kodeverk.dev.intern.nav.no/api/v1/kodeverk/typer/landkoder/kategorier/dummy/kodeverdier

Ja, opprettet database på nytt i stad,.

Oppslag mot felles kodeverk går fint her.
`/api/v1/kodeverk/typer/tidsrom/kategorier` gir resultat her også, men det gjør ikke f.eks. `/api/v1/kodeverk/typer/skadetype/kategorier`, som sagt. Kan ikke helt se hva forskjellen er sånn databasemessig.

Ser også at militær ligger i svaret fra `/api/v1/kodeverk/typer/tidsrom/kategorier`, men kan ikke se at dette ligger inne i `kategori_type`-tabellen?
Jeg tror det burde legges til noen test cases i `KodeverkControllerIT` som sikrer at dette oppfører seg som det skal..

2022-04-05 08:12 UTC, olsnerik approved these changes

2022-04-05 08:20 UTC, merged